List<Map<String, String>> soundData = [
  {
    'title': 'Aww',
    'soundPath': 'AWW.mp3',
    'imagePath': 'aww.jpg',
    'searchString': 'cute cat sweet',
  },
  {
    'title': 'Crickets',
    'soundPath': 'CRICKETS CHIRPING.mp3',
    'imagePath': 'crickets.jpg',
    'searchString': 'silence chirping night awkward',
  },
  {
    'title': 'Dramatic chipmunk',
    'soundPath': 'Dramatic-chipmunk.mp3',
    'imagePath': 'dramatic_chipmunk.jpg',
    'searchString': 'dun dun dun squirrel dramatic look prairie dog surprise',
  },
  {
    'title': 'Ka-ching!',
    'soundPath': 'KA-CHING.mp3',
    'imagePath': 'ka-ching.jpg',
    'searchString': 'cash money cashier dough rich',
  },
  {
    'title': 'Nope',
    'soundPath': 'NOPE.mp3',
    'imagePath': 'nope.jpg',
    'searchString': 'soldier tf2',
  },
  {
    'title': 'Record scratch',
    'soundPath': 'RECORD SCRATCH.mp3',
    'imagePath': 'record_scratch.jpg',
    'searchString': 'stop wait freeze',
  },
  {
    'title': 'Rubber duck',
    'soundPath': 'RUBBER DUCK.mp3',
    'imagePath': 'rubber_duck.jpg',
    'searchString': 'bath squeak',
  },
  {
    'title': 'Suddenly!',
    'soundPath': 'SUDDEN SUSPENSE.mp3',
    'imagePath': 'sudden_suspense.jpg',
    'searchString': 'surprised cat sudden suspense',
  },
  {
    'title': 'Suspense',
    'soundPath': 'SUSPENSE #2.mp3',
    'imagePath': 'suspense.jpg',
    'searchString': 'scary suspense horror',
  },
  {
    'title': 'To be continued...',
    'soundPath': 'TO BE CONTINUED.mp3',
    'imagePath': 'to_be_continued.jpg',
    'searchString': 'jojo roundabout meme',
  },
  {
    'title': 'Windows Error',
    'soundPath': 'WINDOWS XP ERROR.mp3',
    'imagePath': 'windows_error.jpg',
    'searchString': 'wrong broken computer',
  },
  {
    'title': 'Windows start up',
    'soundPath': 'WINDOWS XP START UP.mp3',
    'imagePath': 'windows_startup.jpg',
    'searchString': 'turn on wake up computer',
  },
  {
    'title': 'Ain\'t nobody got time for that',
    'soundPath': 'AINT NOBODY GOT TIME FOR THAT.mp3',
    'imagePath': 'no_time.jpg',
    'searchString': 'tv meme',
  },
  {
    'title': 'John Cena',
    'soundPath': 'AND HIS NAME IS JOHN CENA.mp3',
    'imagePath': 'john_cena.jpg',
    'searchString': 'and his name is john cena wwe',
  },
  {
    'title': 'Ba dum tss',
    'soundPath': 'BA DUM TSS.mp3',
    'imagePath': 'badums.jpg',
    'searchString': 'joke drums troll face',
  },
  {
    'title': 'Bruh',
    'soundPath': 'BRUH.mp3',
    'imagePath': 'bruh.jpg',
    'searchString': 'bro frustration disappointment meme',
  },
  {
    'title': 'Burp',
    'soundPath': 'BURP.mp3',
    'imagePath': 'burp.jpg',
    'searchString': 'simpsons barney cartoon',
  },
  {
    'title': 'Wrong',
    'soundPath': 'BUZZER OR WRONG ANSWER.mp3',
    'imagePath': 'wrong.jpg',
    'searchString': 'cross',
  },
  {
    'title': 'Cartoon laugh',
    'soundPath': 'CARTOON LAUGH.mp3',
    'imagePath': 'chip.png',
    'searchString': 'chip n dale cartoon funny',
  },
  {
    'title': 'Zoidberd woop',
    'soundPath': 'DR ZOIDBERG WOOP.mp3',
    'imagePath': 'zoid.jpg',
    'searchString': 'futurama cartoon',
  },
  {
    'title': 'Crowd cheering',
    'soundPath': 'CROWD CHEERING.mp3',
    'imagePath': 'crowd_cheer.jpg',
    'searchString': 'success',
  },
  {
    'title': 'Doh',
    'soundPath': 'D\'OH.mp3',
    'imagePath': 'doh.jpg',
    'searchString': 'simpsons homer cartoon',
  },
  {
    'title': 'Denied',
    'soundPath': 'DENIED.mp3',
    'imagePath': 'denied.jpg',
    'searchString': 'fail rejected',
  },
  {
    'title': 'Drum roll',
    'soundPath': 'DRUM ROLL.mp3',
    'imagePath': 'drum_roll.jpg',
    'searchString': 'anticipation',
  },
  {
    'title': 'DUN DUN DUN',
    'soundPath': 'DUN DUN DUNNN.mp3',
    'imagePath': 'dun_dun.jpg',
    'searchString': 'surprise cat',
  },
  {
    'title': 'Fail',
    'soundPath': 'FAIL.mp3',
    'imagePath': 'fail_horn.png',
    'searchString': 'fail horn mistake',
  },
  {
    'title': 'Get over here!',
    'soundPath': 'GET OVER HERE.mp3',
    'imagePath': 'get_over_here.jpg',
    'searchString': 'scorpion mortal combat game videogame',
  },
  {
    'title': 'Ha! Gay!',
    'soundPath': 'HA GAY.mp3',
    'imagePath': 'ha_gay.jpg',
    'searchString': 'ha gayyyyy gaayy meme',
  },
  {
    'title': 'Ha! Got em',
    'soundPath': 'HA GOT EMM.mp3',
    'imagePath': 'got_em.jpg',
    'searchString': 'deez nuts',
  },
  {
    'title': 'HA HA',
    'soundPath': 'HA HA (NELSON).mp3',
    'imagePath': 'ha_ha.jpg',
    'searchString': 'simpsons laugh cartoon',
  },
  {
    'title': 'Heart beat',
    'soundPath': 'HEART BEAT.mp3',
    'imagePath': 'heart_beat.jpg',
  },
  {
    'title': 'Heavenly choir',
    'soundPath': 'HEAVENLY CHOIR.mp3',
    'imagePath': 'heaven.jpg',
    'searchString': 'good god happy satisfaction',
  },
  {
    'title': 'Illuminati',
    'soundPath': 'ILLUMINATI.mp3',
    'imagePath': 'illuminati.jpg',
    'searchString': 'x files x-files mystery',
  },
  {
    'title': 'Inception horn',
    'soundPath': 'INCEPTION FOG HORN.mp3',
    'imagePath': 'inception.jpg',
    'searchString': 'suspense',
  },
  {
    'title': 'Mario',
    'soundPath': 'MARIO HERE WE GO.mp3',
    'imagePath': 'mario.jpg',
    'searchString': 'game videogame here we go',
  },
  {
    'title': 'MGS Alert',
    'soundPath': 'MGS ALERT.mp3',
    'imagePath': 'alert.jpg',
    'searchString': 'game videogame surprise',
  },
  {
    'title': 'God please no',
    'soundPath': 'NO GOD PLEASE NO.mp3',
    'imagePath': 'no.png',
    'searchString': 'meme no god noooo',
  },
  {
    'title': 'OMG, who the hell cares',
    'soundPath': 'OMG WHO THE HELL CARES.mp3',
    'imagePath': 'peter_who_cares.jpg',
    'searchString': 'peter griffin cartoon family guy',
  },
  {
    'title': 'Sad violin',
    'soundPath': 'SAD MUSIC #2.mp3',
    'imagePath': 'tiny_violin.jpg',
    'searchString': 'sadness fail',
  },
  {
    'title': 'Flintstone scrambling',
    'soundPath': 'SCRAMBLING - FRED FLINTSTONE.mp3',
    'imagePath': 'flintstone.jpg',
    'searchString': 'cartoon run',
  },
  {
    'title': 'Somebody toucha my spaghet',
    'soundPath': 'somebody-toucha-my-spaghet.mp3',
    'imagePath': 'touch_my_sphaget.png',
    'searchString': 'meme somebody touched my',
  },
  {
    'title': 'A few moments later',
    'soundPath': 'SPONGEBOB TIME CARDS - A FEW MOMENTS LATER.mp3',
    'imagePath': 'few_moments.jpg',
    'searchString': 'spongebob cartoon',
  },
  {
    'title': 'Eventually',
    'soundPath': 'SPONGEBOB TIME CARDS - EVENTUALLY.mp3',
    'imagePath': 'eventually.jpg',
    'searchString': 'spongebob cartoon',
  },
  {
    'title': 'Meanwhile',
    'soundPath': 'SPONGEBOB TIME CARDS - MEANWHILE.mp3',
    'imagePath': 'meanwhile.jpg',
    'searchString': 'spongebob cartoon',
  },
  {
    'title': 'One eternity later',
    'soundPath': 'SPONGEBOB TIME CARDS - ONE ETERNITY LATER.mp3',
    'imagePath': 'eternity_later.jpg',
    'searchString': 'spongebob cartoon waiting',
  },
  {
    'title': 'Uhhh',
    'soundPath': 'SPONGEBOB TIME CARDS - UHH.mp3',
    'imagePath': 'uhhh.jpg',
    'searchString': 'spongebob cartoon frustration',
  },
  {
    'title': 'Surprise',
    'soundPath': 'SURPRISE MOTHER F!!!!!.mp3',
    'imagePath': 'surprise.jpg',
    'searchString': 'motherfucker surprise meme',
  },
  {
    'title': 'They ask you how you are',
    'soundPath': 'THEY ASK YOU HOW YOU ARE.mp3',
    'imagePath': 'crying.jpg',
    'searchString': 'crying sadness girl',
  },
  {
    'title': 'Titanic flute fail',
    'soundPath': 'TITANIC FLUTE FAIL.mp3',
    'imagePath': 'titanic.jpg',
    'searchString': 'failure epic fail',
  },
  {
    'title': 'Vine boom',
    'soundPath': 'VINE GUN SHOT aka BOOM.mp3',
    'imagePath': 'vine.jpg',
    'searchString': 'boom effect',
  },
  {
    'title': 'Y u always lying',
    'soundPath': 'Y U ALWAYS LYING.mp3',
    'imagePath': 'always_lying.jpg',
    'searchString': 'meme why you always lying',
  },
  {
    'title': 'Yay!',
    'soundPath': 'YAY.mp3',
    'imagePath': 'yay.jpg',
    'searchString': 'success kids happy yayyy',
  },
];
